### PR TITLE
Fix for the new moodel 

### PR DESCRIPTION
**Pull request by avisoftware**
It is not recommended to use a synchronized GET. but for now it is better then nothing

### CODE REVIEW

**Review by desdo09 — DISMISSED** [review]
Some modifications i cant change, please send me a mail to abenathardavid@gmail.com

**Review by desdo09 — COMMENTED** [review]
When i made the extension, the moodle wasnt working good in https, so i made in http
I need to check it

**Review by desdo09 — COMMENTED** [review]
"TWA for feching homework, very ugly"

The proposit of this extension was to learn js and jquery, I admit that some functions its not the way...

**Comment by desdo09** [comment]
I made the update.
Thank you for the https tip.
Reggards

**Comment by avisoftware** [comment]
Thank you very much, on behalf of all the students of JCT!!
This extension is really is very popular..

**Pull request closed without merging**
